### ISSUE TITLE
Caching module appends string ?stage=url to the urls and redirect to login page

### ISSUE THREAD

**Issue by spark-green** [silverstripe/silverstripe-staticpublishqueue#100]
I have recently upgraded my project to SilverStripe v3.7.1 and Iare using StaticPublishQueue (v 3.3.0) module to generate the caching of the website.  I have faced couple of issues with this upgrade, which are as follow

1.	I generate the auto cache on the website daily midnight at 1 am. Ihave noticed that after loading certain pages, when navigating to a second page, the second page will have “?stage=live” appended to the url. This is causing issues with some charts not rendering, some download buttons not working and instead directing to the CMS login screen, and some issues with cookie-based functions. Ihave tried numerous fixes to stop this happening but have been unable to fix this. 

2.	For any already published page, the cache is rebuild again when content of that page is updated and published from the CMS. 
However in this process, the new cached html page is generated on the server but it contains only one single line in it as below

`<meta http-equiv=”refresh” content=”2; URL=’https://www.domain.com.au/Security/Login/?BackURL=pageurl’”>`

So on frontend when user clicks on that page, this forces them to the login page.

I had no such issues with old version of SilverStripe v3.6.  
Has anyone come across this issue with their upgrade ? Can anyone shed any light on what might be causing this or what could be done to fix it?

**Comment by emteknetnz** [comment]
Related https://github.com/silverstripe/silverstripe-staticpublishqueue/issues/102

**Comment by dhensby** [comment]
I'm not sure if this is fixed, but I'm afraid v3 is out of support now
