### ISSUE TITLE
Job stalls when setting chunk_size lower than the total amount of urls [SS4.3]

### ISSUE THREAD

**Issue by Valandur** [silverstripe/silverstripe-staticpublishqueue#103]
I noticed that when setting 
```yaml
SilverStripe\StaticPublishQueue\Job\StaticCacheFullBuildJob:
  chunk_size: 10
```
And running the `StaticCacheFullBuildJob` task the job is marked as `Job stalled after ...` after building the first chunk of URLs.

I believe this happens because of [this if check in queuedjobs](https://github.com/symbiote/silverstripe-queuedjobs/blob/master/src/Services/QueuedJobService.php#L881) which checks the `currentStep` on the job, which is never increased.

Adding `$this->currentStep++;` to the `StaticCacheFullBuildJob` [for example after this line](https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/master/src/Job/StaticCacheFullBuildJob.php#L68) makes the job work as intended.

I can submit a PR for this, but I'm not sure that's the right place to increase the step count, and it would probably also need some sanity checks.

**Comment by dhensby** [comment]
This is now fixed (in v5 anyway)
