### ISSUE TITLE
Job processing doesn't indicate progress, URL sanitisation missing

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-staticpublishqueue#107]
Static cache jobs processing doesn't indicate job progress which may result in stale jobs.

URL sanitisation is missing.

## Related pull requests

* https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/104
* https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/130

**Comment by dhensby** [comment]
fixed
