### ISSUE TITLE
Expose PathToURL function

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-staticpublishqueue#109]
We already have `URLtoPath` publicly available and it would be handy to also have `PathToURL` available so we have both transformations covered. This is useful when building custom UI or management tools for static publishing as the default job interface is pretty basic.

Fixed in https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/108

**Comment by emteknetnz** [comment]
Since the associated PR is merged, I'm closing this issue

Thanks for your contribution!
