### ISSUE TITLE
Documentation for command to run StaticCacheFullBuildTask incorrect

### ISSUE THREAD

**Issue by dirtybirdnj** [silverstripe/silverstripe-staticpublishqueue#114]
Hello, I am trying to implement this module on a site that's using Silverstripe 4.4

The documentation says that this is the way to run the task that intitually builds the cache:

`./path/to/sake dev/tasks/StaticCacheFullBuildTask`

However this gives me errors about the task not existing. I tried running `./vendor/bin/sake dev/tasks` to get a list of all tasks... and after grepping for `Static` I found it! The command appears totally different here:

` * SilverStripe\StaticPublishQueue\Task\StaticCacheFullBuildTask: sake dev/tasks/SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask`

To actually get it to run via CLI I have to do:

`./vendor/bin/sake dev/tasks/SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask`

Let me know if I'm doing something wrong or this is some info in the docs that should be updated.

**Comment by dhensby** [comment]
I think there are two solutions:

1. Fix the docs
2. Fix the command to actually execute under the correct path - I think this can be done by setting a config value

**Comment by madmatt** [comment]
This has been fixed by #131 (by adjusting the documentation).
