### ISSUE TITLE
IDEA: increase speed significantly by preparing the gzip version of the HTML

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-staticpublishqueue#117]
I found on a site that it worked dramatically faster if I pre-gzipped the html, as described here ...  https://ma.ttias.be/pre-compress-content-apache-avoid-compressing-every-request/. 

Is that an idea?

**Comment by dhensby** [comment]
This could be implemented as a middleware, I suppose. I'm a bit hesitant to add lots more middleware to our stack though...

**Comment by dhensby** [comment]
I'd also be very surprised if having PHP compress the HTML was faster than apache doing it. I can understand about pre-gziping static assets (that can be part of your build/release process) but the dynamic HTML being pre-gzipped; I'd like to see some proof that PHP is faster than apache/nginx/google-pagespeed

The article you link to doesn't actually make any recommendation or comparisons around having PHP compress dynamically generated HTML vs apache, it only touches on static assets.

I think i'm going to close this as really I think the amount of maintenance burden of having to have PHP do this in a non-buggy way is going to greatly outweigh any speed benefits (which I'm skeptical about anyway)

**Comment by sunnysideup** [comment]
It is not about the PHP doing it. I would just use gzip application to gzip it ;-))) The key is that this module outputs dynamic content to HTML to:
* make the site faster
* lower demands on the server
What I am saying is that if you output to gzipped HTML rather than HTML you will double the improvements you are trying to make.  
I will fork this module and add two lines (hopefully!)  to achieve this.

**Comment by sunnysideup** [comment]
Thank you for looking at this ticket.

**Comment by sunnysideup** [comment]
Before:

![image](https://user-images.githubusercontent.com/167154/86525193-130c2d80-bed8-11ea-8d06-99d775da8f11.png)

**Comment by sunnysideup** [comment]
AFTER:
![image](https://user-images.githubusercontent.com/167154/86525487-de9a7080-bedb-11ea-8a1c-f4a17941e03d.png)

**Comment by sunnysideup** [comment]
The comparisons above are between straight SS and pre-compressed cached HTML.

On average it takes around ~25ms to download pre-compressed cached HTML (50kb page).

When you remove the gzip pre-compression, it is around 30ms.  So the speed increase is around 20%.  Obviously, it is also lighter on the server.

For this, I made minimal changes to the module (basically a couple of lines of structural changes to achieve this).
