### ISSUE TITLE
SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask fails to create ErrorPage(s)

### ISSUE THREAD

**Issue by hklitzke** [silverstripe/silverstripe-staticpublishqueue#128]
While looping through all pages, pages of type ErrorPage are fetched as well. Those are not created and the task ends up in state "broken". Calling dev/tasks/ProcessJobQueueTask again (e.g. later to process other tasks) ends up in Notice that a broken task is in the queue so noting is processed.

Should it be the right solution to exclude ErrorPages from the task?

kind regards
Holger

**Comment by bergice** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-staticpublishqueue/issues/129
