### ISSUE TITLE
SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask fails on ErrorPages

### ISSUE THREAD

**Issue by hklitzke** [silverstripe/silverstripe-staticpublishqueue#129]
While looping through all pages, pages of type ErrorPage are fetched as well. Those are not created and the task ends up in state "broken". Calling dev/tasks/ProcessJobQueueTask again (e.g. later to process other tasks) ends up in Notice that a broken task is in the queue so noting is processed.

Should it be the right solution to exclude ErrorPages from the task?

kind regards
Holger

**Comment by ssmarco** [comment]
I got my pull request here https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/127 which works with error pages.

**Comment by dhensby** [comment]
I don't see this error with v5 of the module

**Comment by sheadawson** [comment]
I do get this error with v5. Had to override `urlsToCache` to filter error pages

**Comment by lars-lemon8** [comment]
I do not see this error with v5.3.
