### ISSUE TITLE
Publishing engine trigger / recursive publish

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-staticpublishqueue#134]
# Publishing engine trigger / recursive publish

Publishing engine triggers `onAfterPublish` which sometimes causes issues with pages containing lot of nested models (like blocks) which contribute to the URL collection. These models need to be published before to hook kicks in in order to produce URLs.

Fixed in https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/133

**Comment by maxime-rainville** [comment]
@mfendeksilverstripe Did https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/133 completely resolve this issue?

Do you need us to tag a release?

**Comment by mfendeksilverstripe** [comment]
Yes, this issue can be closed. We don't need a tag release for this though ;-)

**Comment by michalkleiner** [comment]
Why not create a patch tag, @mfendeksilverstripe?

**Comment by maxime-rainville** [comment]
Looks like the PR adds new APIs, so it probably should be a minor release instead of a patch. Do you guys want me to tag 5.1.0 from master?

https://github.com/silverstripe/silverstripe-staticpublishqueue/compare/5.0.0...master

**Comment by mfendeksilverstripe** [comment]
I was hoping to get my [other PR](https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/132) in there as well but if it's easier for you to tag the release with just these changes that's fine too.
