### ISSUE TITLE
Revert errant commit and update documentation

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-staticpublishqueue#144]
https://github.com/silverstripe/silverstripe-staticpublishqueue/commit/2f05ec1ec3ca0837b258564dc30034676f2d67d1 was pushed directly to the `5` branch without going through the peer review process. It was made to pull the code into agreement with [the documentation](https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/2f05ec1ec3ca0837b258564dc30034676f2d67d1/docs/en/building_the_cache.md?plain=1#L16-L29)

There are some backwards compatibility concerns around this commit. It needs to be reverted, and the documentation needs to be updated to match the current state of the code.

## Acceptance criteria
- [x] 2f05ec1ec3ca0837b258564dc30034676f2d67d1 is reverted
- [x] Documentation has the correct path

## Notes:
A follow up card [has been created](https://github.com/silverstripe/silverstripe-staticpublishqueue/issues/145) to re-introduce the change in the next (CMS 5 compatible) major release line.

**Comment by michalkleiner** [comment]
PR merged
