### ISSUE TITLE
staticpublisher queued job fails in some circumstances

### ISSUE THREAD

**Issue by lars-lemon8** [silverstripe/silverstripe-staticpublishqueue#146]
Running into problems with SS4.11 / Fluent V6 in combination with the Static Publisher.

Situation:
- Fluent 6 
- SS 4.11
- Running in CLI
- Empty Job queue
- No configuration added for staticpublisher (no urlsToCache() ).

**Run StaticCacheFullBuildTask**  -->  added to the queue for immediate processing
**Run ProcessJobQueueTask** -->  Argument #1 ($value) must be of type Countable|array, null given {"exception":"[object] (TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, null given at /data/site/vendor/silverstripe/staticpublishqueue/src/Job.php:102)"

When I re-publish a page in the CMS,  it gets added to the queue and publishes correctly if I process the queue again.

If I try to run publisher tasks in the CMS jobs UI itself ,  the task runs,  but takes a loooooong time and kills the session. Will have to look at the logs to see what is happening.

**Comment by guci0** [comment]
Hi lars, check this:

first of all check your Job file and compare to:
https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/2f05ec1ec3ca0837b258564dc30034676f2d67d1/src/Job/StaticCacheFullBuildJob.php#L43

There is a difference from composer install, I don't keno why...

**Comment by lars-lemon8** [comment]
@GuySartorelli , thanks, sure , will do ! 

Yeah, everything is in CLI , my remark about the CMS UI was meant as a sidenote ,  and is confusing, sorry about that.

**Comment by lars-lemon8** [comment]
@GuySartorelli 
I left Fluent out of the equation in this example. My environment is PHP8.

### 1> Setup SS
- composer create-project silverstripe/installer .
- create DB / setup ENV file
- setup default user / pwd
- dev build -> load site -> works

### 2> Install static publisher
- composer require silverstripe/staticpublishqueue
- run a dev build

### 3> Tests (all from browser, no UI)
- run /dev/tasks/SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask (in browser), the job gets added with 0/0 tasks

![image](https://user-images.githubusercontent.com/15701748/193764564-4d5ba706-c53c-455f-9d49-e6c95a8d49c5.png)

![image](https://user-images.githubusercontent.com/15701748/193764679-8da3a9d9-5ce2-4abb-a79e-f1af9ac9f989.png)

- Press 'play' on job , results in 'broken'

![image](https://user-images.githubusercontent.com/15701748/193764899-d1c32e3e-32a0-4e2d-b1e0-ac16f17d8700.png)

- Messages are empty (which makes sense)
![image](https://user-images.githubusercontent.com/15701748/193764970-b11bba3b-e65a-44a9-8d13-b9bd89b49c8a.png)

**Comment by satrun77** [comment]
I have the same error `count(): Argument #1 ($value) must be of type Countable|array`. Pull request to resolve it #149

**Comment by guci0** [comment]
I'm already testing on a live server, now there was a problem of access rights (chmods) - files are locked.

/cache and subfolders are fine 775, but .htmls – 600.

Hmmm...

**Comment by lars-lemon8** [comment]
@guci0: It feels quite unlikely your file permission problems have anything to do with this module. 

I have also been testing #149 ,  it fixes this error for me: 

`[2022-10-04 10:07:40] Running Generate static pages for all URLs and others from queue 2. [2022-10-04 10:07:40] error-log.INFO: count(): Argument #1 ($value) must be of type Countable|array, null given {"exception":"[object] (TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, null given at /data/site/vendor/silverstripe/staticpublishqueue/src/Job.php:102)"} []`


A new problem arises however;  the StaticCacheFullBuildJob now gets stuck in 'waiting' after this message:
` error-log.WARNING: Job releasing memory and waiting (256.01 MB used) [] []

`

**Comment by lars-lemon8** [comment]
Okay. New version is released.  The results are entirely different now.   It got a lot better, but still refuses to complete a StaticCacheFullBuildJob.  

Closing this ticket for now.  Will spin up a new one with a clean test scenario if I have the time.
