### ISSUE TITLE
URL's get stage appended in fullbuildtask if they are included in urlsToCache() method

### ISSUE THREAD

**Issue by lars-lemon8** [silverstripe/silverstripe-staticpublishqueue#159]
Been digging around a bit, and I have isolated the problem below:

When running the static cache full build task (through the cli),  any URLs that are included in urlsToCache() methods in a page class get ?stage=Stage added to the URL.   These cannot be processed by the task and will result in the Static Cache Full Build task to end up paused. 

So for example, the URL below will end up in the list of URL's to be processed as '/?stage=Stage'
```
  public function urlsToCache()
    {
        return [HomePage::get()->first()->Link()=>1];
    }
```

Related issue:
#150

**Comment by GuySartorelli** [comment]
Is this actually different to #150? Or are they both symptoms of the same underlying issue?

**Comment by GuySartorelli** [comment]
@lars-lemon8 If you can't point out _how_ they're different, I think it's easiest to just treat them as the same issue.

**Comment by GuySartorelli** [comment]
Closing with the assumption they're effectively the same issue. If you can indicate how they're different I'll reopen.
