### ISSUE TITLE
Enhancement: Provide config to allow updating of children when a parent updates

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-staticpublishqueue#166]
## Description

We quite commonly include page elements that directly relate to the parent (or parents) of that page. EG: breadcrumbs.

It would be nice if there was a config available to enable this out of the box. I was thinking that perhaps it would be good to have a few options:

* `0`: Do not update children (maintains BC)
* `1`: Only update the direct children (not recursive)
* `2`: Recursively update all children

## PRs
- #168

**Comment by GuySartorelli** [comment]
@chrispenny @emteknetnz This is connected to #168, but that PR is for #165... is there a PR for this issue?

**Comment by chrispenny** [comment]
@GuySartorelli These new configurations were added as part of #168 
https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/168/files#diff-01312d7ef3a09d76a5c905f50e35b2e3776cba9f211f3f021b29acace9656680R27-R33
