### ISSUE TITLE
Enhancement: Provide config to disable the updating of a parent when a child updates

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-staticpublishqueue#167]
## Description

I suspect that some projects **do** have a use for this mechanism, but personally I'm yet to need this, and I usually remove it from our functionality to save on that small amount of processing effort.

I was thinking that it would be good to have a few options:

* `0`: Do not update children
* `1`: Only update the direct parent
* `2`: Recursively update all parents

## PRs
- #168

**Comment by GuySartorelli** [comment]
@chrispenny @emteknetnz  This is connected to #168, but that PR is for #165... is there a PR for this issue?

**Comment by chrispenny** [comment]
@GuySartorelli These new configurations were added as part of #168 
https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/168/files#diff-01312d7ef3a09d76a5c905f50e35b2e3776cba9f211f3f021b29acace9656680R27-R33
