### ISSUE TITLE
Add the ability to exclude certain response codes from being statically cached

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-staticpublishqueue#172]
## Scenario

1) Create a top level page (`page-1`)
2) Create a child page (`page-2`) under `page-1`
3) Unpublish `page-1`
4) Publish `page-2`

### CMS behaviour

When users attempt to browse to `page-1/page-2` on the frontend, the page will 404 since the parent page is not published.

### Static publisher behaviour

* When `page-2` is published a job will be created to static cache that URL.
* The job will complete successfully, and a static cache of a `404` page will be created.

## Proposal

I would say for most of my projects, there is no value in creating static cache files to serve 404 responses for specific URLs - our 404 error page is already statically cached and performs this role perfectly well.

We would like the ability to exclude certain response codes from having static cache files generated for them.

Attempted a fix in this commit:
https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/168/commits/90a22ffd79d61cc6f5c60d9ceef70deebfe422cb

Worked in practical testing, but I couldn't get the unit tests to respect my config change:
https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/168#issuecomment-1679556152

## Acceptance criteria
- Developers have the option to not cache specific pages based on the HTTP status code.
- Documentation is updated to explain how to use this feature.
 
## Note
- It might be advisable to turn this behaviour on by default in the next major release. Maybe me create a follow up card and add it to the CMS 6 milestone (https://github.com/silverstripe/silverstripe-staticpublishqueue/issues/179)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11082
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/178
- https://github.com/silverstripe/developer-docs/pull/413

**Comment by GuySartorelli** [comment]
@emteknetnz You've moved this to "awaiting" but it's not assigned to anyone. I'm assigning to you as the person who moved it. I'm guessing it's just in the wrong place though given there's nothing obvious we're waiting _for_? No comments etc?

**Comment by emteknetnz** [comment]
Card is being looked at by another team so I'm moved it to awaiting so that CMS squad wouldn't pickup and end up double handling - context https://silverstripeltd.slack.com/archives/CLXKD9X51/p1693182771397469

**Comment by GuySartorelli** [comment]
Sweet.
That context says they'll look into it "in the next few weeks." - so if this issue hasn't been updated after say a month we need to follow up.
