### ISSUE TITLE
Requesting a valid URL for Subsite A from Subsite B creates a redirect loop

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-staticpublishqueue#25]
If /about/ is a valid URL for subsite-a.com but not subsite-b.com, accessing subsite-b.com/about/ should result in a 404 but instead creates a 301 redirect loop.

**Comment by dhensby** [comment]
I'm not sure if this is still an issue, but it's very old and there hasn't been any other work on this, so I think it can be closed. please let me know if I'm wrong
