### ISSUE TITLE
static files end in .html but contain PHP, causing the documented static-main.php to not work

### ISSUE THREAD

**Issue by ss23** [silverstripe/silverstripe-staticpublishqueue#31]
This will use `readfile` if the extension is `.html`, which it is, but it's not really HTML content.

We should probably be using `.php` extensions if it's PHP, and the documented `static-main.php` will also need to change to support `stale.php` files.

**Comment by ss23** [comment]
@stojg has advised to generate these files as .php and add file-static.php to static main example.

**Comment by maxime-rainville** [comment]
Need to validate if this still affects SS4

**Comment by dhensby** [comment]
I believe this was fixed for the 4.0.0 rewrite
