### ISSUE TITLE
If an item is added with an empty URL to be cached, SiteTreeFullRebuildEngine goes into an infinite loop

### ISSUE THREAD

**Issue by ss23** [silverstripe/silverstripe-staticpublishqueue#32]
Certainly there is a bug if `urlsToCache` is returning an empty URL, but it happened in a project I'm working on.

When given the empty string, `HTTP::setGetVar` will assume you mean the current page. Since this is the `SiteTreeFullRebuildEngine` task, it'll add itself again, causing an infinite loop.

There is a fix I can submit as a PR -- simply checking if the URL is empty, however, I wanted to raise a question over the use of `HTTP::setGetVar` here:
What is the point in it? This is causing an additional issue where cached pages with anchor links are showing the `_ID` and `_ClassName` parameters, which should be hidden from visitors of the site. I have raised #33 regarding this particular bug separately, but knowing the outcome of that bug will decide what to do here.

**Comment by ss23** [comment]
@stojg has advised to add a check for empty URLs to skip them.

**Comment by dhensby** [comment]
pretty sure this has been fixed 🤞
