### ISSUE TITLE
Use of HTTP::setGetVar causes cached pages to include these parameters in anchor links

### ISSUE THREAD

**Issue by ss23** [silverstripe/silverstripe-staticpublishqueue#33]
The use of the function seems dubious to me in the first place.

**Comment by ss23** [comment]
@stojg has advised to remove these variables (or something similar) when doing the actual page generation, as they're required for static subsites

**Comment by maxime-rainville** [comment]
Need to validate if this still applies to SS4.

**Comment by dhensby** [comment]
Pretty sure this has been fixed
