### ISSUE TITLE
Avoid deleting combined_files on flush

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-staticpublishqueue#61]
Discussed in core under https://github.com/silverstripe/silverstripe-framework/issues/4553. It's debatable if this should go into core (if flush should delete combined files at all). But: We should apply the patch by default to this module since it'll always cause problems by default, which is really bad developer experience :D https://gist.github.com/tractorcow/cccf035d4cd13a0de62edf69e7a63126

/cc @edlinklater @tractorcow

**Comment by lars-lemon8** [comment]
This issue does not seem relevant anymore (SS4 has the Requirements.disable_flush_combined setting).

Should we close this ticket ?
