### ISSUE TITLE
Conflict with partial caching silverstripe

### ISSUE THREAD

**Issue by paul-ang** [silverstripe/silverstripe-staticpublishqueue#67]
Hi,

It looks like this module is not compatible with partial caching? When I try to rebuild the static cache by running the task in the CLI, I ended up with the error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes). However, once I deleted the silverstripe-cache folder (which is used by the partial cache), it works.

Any idea why is this a problem?

Thank You.
Best regards.

**Comment by dhensby** [comment]
Hmmm - it seems there's a memory leak somewhere that must be causing you to run out of memory - it's a bit strange that it doesn't happen when your manifest/template caches are cleared, though :/

Is you partial caching storing large datasets?

**Comment by mrvickiee** [comment]
nope, I am just caching the content of my blog post.

**Comment by mrvickiee** [comment]
Any update on this?

**Comment by dhensby** [comment]
@mrvickiee I think this issue is quite specific and difficult for a third party to debug or diagnose - have you done any debugging to try and find some root cause of the issue?

**Comment by dhensby** [comment]
have you been able to replicate this on a "vanilla" site?

**Comment by wernerkrauss** [comment]
@elkebe could be related to https://github.com/silverstripe/silverstripe-framework/issues/8572 which was fixed but not released.

@mrvickiee Also can you please double check, that you run the same php version from CLI and Web? I encountered troubles on my server, when deployment accidently ran another php version than apache, unrelated to static publishing.

**Comment by elkebe** [comment]
@wernerkrauss If it helps to know, I'm running PHP 7.0.30 via MAMP on my dev machine and PHP 7.0 on server.

**Comment by dhensby** [comment]
closing this as stale and likely no longer a bug
