### ISSUE TITLE
Status 'Broken' when forcing html extension

### ISSUE THREAD

**Issue by DrMartinGonzo** [silverstripe/silverstripe-staticpublishqueue#71]
I get `[ERROR] Job stalled after 4 attempts - please check` when fileExtension is set to `html` in config. Does anyone have the same problem ?
Files are correctly generated though.

**Comment by DrMartinGonzo** [comment]
Nevermind, can't reproduce it.

**Comment by MightyMerio** [comment]
I just got that same error when testing a new install on local.  Was this when you executed the job manually from the jobs list, or via cron job?
