### ISSUE TITLE
Index.html gets deleted when doing StaticCacheFullBuildTask

### ISSUE THREAD

**Issue by DrMartinGonzo** [silverstripe/silverstripe-staticpublishqueue#72]
index.html always end up in `$this->jobData->URLsToCleanUp`
Anyone else seeing this behavior ?

**Comment by dhensby** [comment]
Which version of the module?

**Comment by DrMartinGonzo** [comment]
Arg, sorry. Latest released Silverstripe 4 version : 4.0.0-alpha.1

**Comment by dhensby** [comment]
cc @andrewandante

**Comment by andrewandante** [comment]
@DrMartinGonzo could you try pulling in the changes in #73 and testing again please? I've run it locally and it seems fine, but would be good to confirm.

**Comment by DrMartinGonzo** [comment]
Works on my side too :) Thanks !

**Comment by dhensby** [comment]
alpha.2 released :)
