### ISSUE TITLE
staticrequesthandler.php should get $cacheDir from FilesystemPublisher.php

### ISSUE THREAD

**Issue by pxwee5** [silverstripe/silverstripe-staticpublishqueue#74]
silverstripe-staticpublishqueue/includes/staticrequesthandler.php

should get its $cacheDir from

silverstripe-staticpublishqueue/src/Publisher/FilesystemPublisher.php

No reason why we should specify the same directories in 2 places.

**Comment by andrewandante** [comment]
The reason it's defined in both places is that we want to avoid booting the SilverStripe app if we can. If we get the cache dir from `FilesystemPublisher.php`, then we have to boot the config to see whether it has been overridden in yaml, which largely negates the purpose of the module. At least that is my understanding, @dhensby can confirm?

**Comment by dhensby** [comment]
This is pretty much answered  here: https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/master/docs/en/advanced_configuration.md#further-improved-performance

> Static Publish Queue has been built to balance (developer) usability (and featureset) with performance. As such there are ways to get better performance from the module if you're willing to accept some limitations / drawbacks.

As @andrewandante we'd need to boot the SS framework to get the config data out and that pretty much defeats the purpose of the module.

At the moment this is a compromise, but an intended one.
