### ISSUE TITLE
Strange error with this module with HTTPS 

### ISSUE THREAD

**Issue by pxwee5** [silverstripe/silverstripe-staticpublishqueue#77]
In my dev and test environments, this plugin works flawlessly. However when I went live with `SS_BASE_URL` set to a url with https protocol, I get the following error.

`
Wed Apr 18 05:19:04 2018 (ss[error]) :: [] error-log.WARNING: E_WARNING: rmdir(/app/.cache): Permission denied {"code":2,"message":"rmdir(/app/.cache): Permission denied","file":"/app/vendor/silverstripe/assets/src/Filesystem.php","line":106} []
`

Apparently `remove_folder_if_empty` is called for some reason. When I revert `SS_BASE_URL` to a http protocol, cache rebuilds without issue.

**Comment by andrewandante** [comment]
Hi @pxwee5, can you take a look at #75 (and the subsequent fix) and see if that resolves your problem? I can't see it being HTTPS related - I'm not sure how that would make sense - but we have removed the `remove_folder_if_empty` call in #76

**Comment by dhensby** [comment]
I guess we should tag a release :)

**Comment by dhensby** [comment]
done - https://github.com/silverstripe/silverstripe-staticpublishqueue/releases/tag/4.0.0-beta.1

**Comment by pxwee5** [comment]
Tried the new release. It completes the task without error but weirdly no cache were created. 
This didn't happen if SS_BASE_URL is http. What am I missing here?

**Comment by dhensby** [comment]
is the cache dir writable? What does the output of the queuedjob have?

**Comment by pxwee5** [comment]
cache_dir is writable, because it's working on all of my other environments. 

Output:
```
[2018-04-18 21:39:00][INFO] Building 5 URLS
[2018-04-18 21:39:00][INFO] array (
0 => 'http://www.url.com/',
1 => 'http://www.url.com/page-not-found/',
2 => 'http://www.url.com/server-error/',
3 => 'http://www.url.com/about/',
4 => 'http://www.url.com/info/',
)
[2018-04-18 21:39:03][INFO]
[2018-04-18 21:39:03][INFO]
```

**Comment by dhensby** [comment]
> cache_dir is writable, because it's working on all of my other environments.

That doesn't mean it's writable on your live environment...

Your output is a bit strange because those URLs are HTTP and not HTTPS but you say you're building an HTTPS site - so maybe there's something going on to completely mess the URLs up... Though none of that should affect the ability to generate the cache...

What are the permissions on the cache folder?

**Comment by pxwee5** [comment]
`drwxr-xr-x`

**Comment by pxwee5** [comment]
User is in the group that can write the folder. It is the user who created the folder btw. 

`drwxr-xr-x  2 test test 4096 Apr 19 11:44 cache`

`domain_based_caching` is not on as well, never made any changes to that setting before.

**Comment by andrewandante** [comment]
Alright, then I suspect that the URLs being generated with HTTP while expecting HTTPS are what is causing the issue - thought we've not had any other reports of that. Will attempt to test locally.

**Comment by andrewandante** [comment]
@pxwee5 just to update you, I have managed to replicate this locally. Working on a bug fix now

**Comment by andrewandante** [comment]
@pxwee5 we think we've found a bug in core with protocols and CLI runners. In the meantime, you should be able to set `Director::alternate_base_url` to your `SS_BASE_URL` to get around the problem - will link to the core PR once it is made
