### ISSUE TITLE
Feature request:  add timestamp to published html

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/silverstripe-staticpublishqueue#78]
Whilst adding the static publisher to a site, and particularly whilst developing additional code around it, I found it very useful to be able to see when pages were actually being updated (or not as the case may be).

To get around this, I put a simple hack in place which adds the current timestamp to the end of the HTML as a comment:

In `FilesystemPublisher::publishPage()`:

```
protected function publishPage($response, $url)
    {
        $success = true;
        if ($path = $this->URLtoPath($url)) {
            if ($this->getFileExtension() === 'php') {
                $phpContent = $this->generatePHPCacheFile($response);
                $success = $this->saveToPath($phpContent, $path . '.php');
            }
            $responseBody = $response->getBody();
            $responseBody = str_replace('</html>', "<!-- ".date('d/m/Y H:i:s')." -->\n</html>", $responseBody);            
            return $this->saveToPath($responseBody, $path . '.html') && $success;
        }
        return false;
    }
```

A few possible questions:

- Should this be active in dev mode (and dev mode only)?
- Should this be a config option to enable?
- Is there a better way to add the timestamp?

**Comment by dhensby** [comment]
I think pushing this into the cached output isn't a great idea. We don't actually have any knowledge that the output is indeed HTML and also adding comments outside the `</html>` is invalid markup, I believe.

I'd go for an approach of adding a header to the response instead. `X-Cached-At` or something... You could extend the default `Publisher` and add the header in `generatePHPCacheFile`.

Are you thinking of creating a PR for this?

**Comment by DorsetDigital** [comment]
I'd be happy to do a PR if we can reach a consensus on the best method.
The issue I can see with adding it to the PHP file is that it might not be generated - this was the case for me.   I had only HTML files enabled, so this was the simplest way.

I take your point about the output possibly not being HTML, in the case of JSON, XML, etc. it wouldn't work - that's why I used a `str_replace()` on the closing HTML tag...  if it wasn't there, it should fail gracefully.   The comments appear before the closing tag, so should still be valid markup

**Comment by crlindsay2** [comment]
instead of injecting it into the html, you could write a LastUpdated (or whatever you want to call it) value before publishing, then have an if statement in the <head> of your doc with the  inside. That way it *should* only be inserted and visible if it's static published, and you're not injecting html.

In theory anyway, i don't know offhand if you can change a db value and have it reflected in the template as part of the publish function.

**Comment by DorsetDigital** [comment]
If the PR is OK, I'll make an update to the docs to reflect the additional config options

**Comment by robbieaverill** [comment]
Thanks @DorsetDigital
