### ISSUE TITLE
Silverstripe 4.1 support

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/silverstripe-staticpublishqueue#81]
At the moment, the dependency for Silverstripe framework is pegged in the 4.0.x branch.  I did a brief bit of testing last night and everything appears to work correctly on a vanilla 4.1 installation.

Is there a wider issue which means that we have to stick with the 4.0.x release at the moment, or can I PR with an update to the dependency version / docs?

**Comment by dhensby** [comment]
@DorsetDigital there shouldn't be anything pegging this to 4.0.x release line of SS framework.

I've checked the `composer.json` and the readme and they both link to to `^4.0.2` (>=4.0.2, <5). 

If there's anywhere that's locking versions down to 4.0 please do submit a PR to amend.

**Comment by DorsetDigital** [comment]
Hmm, OK.  I'll do some more checking then.   I got a bunch of composer errors when I tried to install it on a 4.1 site.  Changing the version constraint to `^4` seemed to cure it.
I'll investigate further.

**Comment by dhensby** [comment]
The travis builds on this module are running against 4.1, so it should definitely be working

**Comment by DorsetDigital** [comment]
Right, apologies.  I've just done it on a clean install and it's installed with no errors.  
Must be something else in the project causing problems.
