### ISSUE TITLE
DeleteStaticCacheJob causes error with array_keys

### ISSUE THREAD

**Issue by pxwee5** [silverstripe/silverstripe-staticpublishqueue#88]
Error message:
`Warning: array_keys() expects parameter 1 to be array, null given in /app/vendor/silverstripe/staticpublishqueue/src/Job.php on line 31 Warning: implode(): Invalid arguments passed in /app/vendor/silverstripe/staticpublishqueue/src/Job.php on line 31`

To replicate:
1. Generate cache using `StaticCacheFullBuildJob`
2. Run `DeleteStaticCacheJob`
3. Error

Occurs in Alpha-2 and Beta-1

**Comment by dhensby** [comment]
I'm pretty sure this has been fixed - please let me know if not
