### ISSUE TITLE
Unable to handle SS4.2.1 URLs that include `stage=Live`

### ISSUE THREAD

**Issue by pxwee5** [silverstripe/silverstripe-staticpublishqueue#89]
```
[
  0 => 'http://url.com/news/press-release-article/?stage=Live',
  1 => 'http://url.com/find-us/?stage=Live'
]
```
I got these when I manually run `SilverStripe\StaticPublishQueue\Job\StaticCacheFullBuildJob`. And no cache files were created in the cache folder.

**Comment by emteknetnz** [comment]
Thanks for submitting this issue.  Could you please clarify what the array above refers to?

**Comment by dhensby** [comment]
fixed in v5
