### ISSUE TITLE
Infinite redirects in cached pages when using silverstripe-fluent

### ISSUE THREAD

**Issue by Valandur** [silverstripe/silverstripe-staticpublishqueue#92]
I wasn't sure whether to submit this issue here or over at silverstripe-fluent, but I can move it if required.

In a project using this module (I'm using composer with `SilverStripe 4.1.2` and this module on `dev-master`) I get pages that contain infinite redirects when using the silverstripe-fluent module. In another project using this module without silverstripe-fluent it works without issues.

The page that is generated as a cached page looks, for example for the page `/de/2018`, like this:

```html
<!doctype html>
<html>
<head>
    <meta http-equiv="refresh" content="1; url=/de/2018/" />
</head>
<body>
<h1>This page has been moved</h1>
<p>Redirecting you to <a href="/de/2018/" title="Click this link if your browser does not redirect you">/de/2018/</a></p>
<script type="application/javascript">setTimeout(function(){
    window.location.href = "/de/2018/";
}, 50);</script>
</body>
</html>
```

Which obviously gets the browser stuck reloading the same page forever.
The weird thing is that it works for the index page (which doesn't contain the language `de` prefix in the URL)

The cached php page that is generated looks like this:
```php
<?php

return array (
  'responseCode' => 301,
  'headers' => 
  array (
    0 => 'content-type: text/html; charset=utf-8',
    1 => 'location: /de/2018/',
  ),
);
```

So it seems that SilverStripe is actually returning a redirect, but when viewing the page normally in my browser I can't witness any redirect happening.

**Comment by phil-quinn** [comment]
@Valandur did you ever figure out a workaround? We are having the same issue with this and fluent.

**Comment by phil-quinn** [comment]
@Valandur I may have found a clue. I was using axllent/silverstripe-trailing-slash which was causing some redirects to happen internally. Once I removed that, it worked great!

**Comment by dhensby** [comment]
is this still a problem?

**Comment by Valandur** [comment]
I personally don't use SilverStripe / PHP much anymore, so I won't be able to comment on this. You may close the issue if required, or I can do that for you.

**Comment by dhensby** [comment]
Thanks for replying. I will close this and can look into it again if it comes up later
