### ISSUE TITLE
Links to resources within public folder broken

### ISSUE THREAD

**Issue by elkebe** [silverstripe/silverstripe-staticpublishqueue#97]
If public folder is used (SS4.2.1) then resource links need to include "public" eg.
`http://domain.com/assets/combined/combined.css`
should be
`http://domain.com/public/assets/combined/combined.css`
and
`http://domain.com/resources/themes/mytheme/css/style.css`
should be
`http://domain.com/public/resources/themes/mytheme/css/style.css`

**Comment by wernerkrauss** [comment]
@elkebe afaik your webroot should point to the public folder if you have one, then it should work out of the box.

I've also seen a special .htaccess in your silverstripe root, that redirects everything to public.

Where does your `index.php` live? it should also be in public.

**Comment by elkebe** [comment]
Thanks @wernerkrauss 
Yes, AFAIK I have index.php in the correct spot. I have the following folder structure:
```
/public/assets/
/public/favicons/
/public/resources/
/public/index.php
```
etc.

Do you have any examples please? I'm also struggling to get staticpublishqueue working consistently (ie. I've managed to get it to generate a cache once). I'm currently just trying to get it to build the initial cache by calling /dev/tasks/ directly or via running the cache build job through the CMS admin Jobs interface. I'm still testing it locally (hence running the tasks directly, rather than as a cron job) as I don't want to install it on my live site until I'm sure its going to give the desired results!

There seems to be some documentation for the SS4 version, but it is quite different to the SS3 version, so I'm a bit unsure how to proceed! Working "out of the box" is well and good, but I seem to get timeout errors when I try to run the full build task in the Jobs admin. Any help/pointers are greatly appreciated!

**Comment by wernerkrauss** [comment]
Where does your development webroot point to? It should point to `/path/to/project/public`, then it should run like expected.

**Comment by elkebe** [comment]
@wernerkrauss thanks. Have figured it out thanks to an answer to my [forum question](https://forum.silverstripe.org/t/static-publisher/1290/6) The use of <% base_tag %> in the template would cause it to default to http://localhost instead of http://localhost:8888 (deleting <% base_tag %> fixes this).

**Comment by wernerkrauss** [comment]
Even if your problem is solved, should we leave this issue open to improve the docs? What do the maintainers think about that?

**Comment by elkebe** [comment]
Up to you... I'd consider the particular issue closed, but maybe it could be relabelled under docs (that certainly would've been quite helpful as the SS4 docs on GitHub are quite different to the SS3 docs on SilverStripe addons)? 

If it helps, more info I'm looking for (but I'll go to the forum for that), is:
1) how to avoid a the jobs timing out
2) problems with member's only pages (they tend to just display as redirect pages)
3) how to get around the default login page/form (which is normally on the main Page.ss).
